version: '2'

services:
  postgres:
    image: postgres:9.6.1-alpine
    environment:
      - POSTGRES_USERNAME=flask_skeleton
      - POSTGRES_DB=flask_skeleton
      - POSTGRES_PASSWORD=mysecretpassword
  flask:
    image: btquanto/docker-flask
    environment:
      - GUNICORN_CONFIG_FILE=scripts/gunicorn_config.py
    ports:
      - 8000:8000
    volumes:
      - ./:/src
    links:
      - postgres
    # command: /bin/bash /src/scripts/flask.sh
