version: '3'

services:
  jekyll:
    image: btquanto/docker-flask
    environment:
      - GUNICORN_CONFIG_FILE=scripts/gunicorn_config.py
    ports:
      - 8000:8000
    volumes:
      - ./:/src
    command: /bin/bash /src/scripts/flask.sh
