version: '2'

services:
  # Data volume
  data:
    image: alpine:3.5
    volumes:
      - ./:/src
    command: /bin/sh
  postgres:
    image: postgres:9.6.1-alpine
    environment:
      - POSTGRES_USERNAME=flask_skeleton
      - POSTGRES_DB=flask_skeleton
      - POSTGRES_PASSWORD=mysecretpassword
  flask:
    image: btquanto/docker-flask-py3:latest
    environment:
      - UWSGI_CONFIG_FILE=uwsgi_config.ini
    ports:
      - 8000:8000
    volumes_from:
      - data
    links:
      - postgres
    # command: /bin/bash -lc "/src/scripts/flask.sh"
